### ISSUE TITLE
Make timestamps configuable

### ISSUE THREAD

**Issue by missinglink** [pelias/logger#1]
I personally would prefer more horizontal space in my logs during debugging; yet I see why timestamps are crucial for server logging.

Can we make the `timestamp` property configurable?

**Comment by sevko** [comment]
I'd prefer more concise time-stamps as well, but it's unfortunately not terribly clean to implement. We'd need to define a custom formatter function, like so:

``` javascript
// yes, we have to reimplement this on our own
var colors = {
    silly: 'white',
    debug: 'magenta',
    verbose: 'cyan',
    info: 'green',
    warn: 'yellow',
    error: 'red'
};

function formatter( log ){
        var timeStr = new Date() /* whatever */;
        return util.format(
            '%s %s %s %s', timeStr, log.label,
            log.level[ colors[ log.level ] ], log.message
        );
}
```

I once tried that in order to implement custom logger-name highlighting/placement in the log message so that I could more easily distinguish between logs from different packages, but ultimately threw it out because it felt a little hacky. If we're in favor of configurable timestamps, though, I'd happily tackle both.

**Comment by sevko** [comment]
Oh, if you're looking to disable timestamps entirely, that's trivial. Working on it.

**Comment by missinglink** [comment]
:+1: awesome, thanks!
